baseURL: https://mistilart.com/
languageCode: en-uk
title : Mistil Art
theme: ankh
author: Mistil Art
canonifyurls: true
enableRobotsTXT: true

permalinks:
  statics: /:title

params:
    author: Mistil Art
    favicon: favicon.ico
    
    description: Tattoo and D&D character art
    header:
        logo: /images/logos/headerlogo.png/
        storeTitle: Store
        storeLink: https://www.redbubble.com/people/MistilArt/shop
        socialmedia:
            - link: https://www.instagram.com/mistil_art/
              icon: instagram
            #- link: https://facebook.com/#
            #  icon: deviantart
            #- link: https://facebook.com/#
            #  icon: discord
            #- link: https://facebook.com/#
            #  icon: d-and-d
            #- link: https://facebook.com/#
            #  icon: d-and-d-beyond
            #- link: https://facebook.com/#
            #  icon: critical-role
            #- link: https://facebook.com/#
            #  icon: etsy
            #- link: https://facebook.com/#
            #  icon: patreon