baseURL: http://example.org/
languageCode: en-uk
title : Mistil
theme: ankh
canonifyurls: true

permalinks:
  statics: /:title

params:
    header:
        #possible values: see icons directory
        socialmedia: 
            - link: https://www.instagram.com/mistil_art/
              icon: instagram
            #- link: https://facebook.com/#
            #  icon: deviantart
            #- link: https://facebook.com/#
            #  icon: discord
            #- link: https://facebook.com/#
            #  icon: d-and-d
            #- link: https://facebook.com/#
            #  icon: d-and-d-beyond
            #- link: https://facebook.com/#
            #  icon: critical-role
            #- link: https://facebook.com/#
            #  icon: etsy
            #- link: https://facebook.com/#
            #  icon: patreon